version: '3'

services:
  models:
    image: tensorflow/serving:latest
    ports:
      - 8501:8501
      - 8500:8500
    volumes:
      - ./app:/app
      - ./models:/models
    command: --model_config_file=/models/models.config --enable_batching

  api:
    build: .
    volumes:
      - ./app:/app
    ports:
      - 8080:8080
    environment:
      ENVIRONMENT: 'test'
      TENSORFLOW_SERVE_ENDPOINT: 'http://models:8501'
    links:
      - 'models:models'

    command: ["/bin/bash", "/usr/local/startup.sh"]
